export const ProtocolFeesAbi = [
  {
    type: 'constructor',
    inputs: [{ name: 'initialOwner', type: 'address', internalType: 'address' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'MAX_PROTOCOL_SHARE_BPS',
    inputs: [],
    outputs: [{ name: '', type: 'uint16', internalType: 'uint16' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'MAX_PROTOCOL_SHARE_OF_SENDER_FEE_PCT',
    inputs: [],
    outputs: [{ name: '', type: 'uint8', internalType: 'uint8' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'MAX_SHARE_BPS',
    inputs: [],
    outputs: [{ name: '', type: 'uint16', internalType: 'uint16' }],
    stateMutability: 'view',
  },
  { type: 'function', name: 'acceptOwnership', inputs: [], outputs: [], stateMutability: 'nonpayable' },
  {
    type: 'function',
    name: 'owner',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'pendingOwner',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'protocolFeeRecipient',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'protocolShareBps',
    inputs: [],
    outputs: [{ name: '', type: 'uint16', internalType: 'uint16' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'protocolShareOfSenderFeePct',
    inputs: [],
    outputs: [{ name: '', type: 'uint8', internalType: 'uint8' }],
    stateMutability: 'view',
  },
  { type: 'function', name: 'renounceOwnership', inputs: [], outputs: [], stateMutability: 'nonpayable' },
  {
    type: 'function',
    name: 'setProtocolFeeRecipient',
    inputs: [{ name: '_protocolFeeRecipient', type: 'address', internalType: 'address' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'setProtocolShareBps',
    inputs: [{ name: '_protocolShareBps', type: 'uint16', internalType: 'uint16' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'setProtocolShareOfSenderFeePct',
    inputs: [{ name: '_protocolShareOfSenderFeePct', type: 'uint8', internalType: 'uint8' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'transferOwnership',
    inputs: [{ name: 'newOwner', type: 'address', internalType: 'address' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'event',
    name: 'OwnershipTransferStarted',
    inputs: [
      { name: 'previousOwner', type: 'address', indexed: true, internalType: 'address' },
      { name: 'newOwner', type: 'address', indexed: true, internalType: 'address' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'OwnershipTransferred',
    inputs: [
      { name: 'previousOwner', type: 'address', indexed: true, internalType: 'address' },
      { name: 'newOwner', type: 'address', indexed: true, internalType: 'address' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'ProtocolFeeRecipientUpdated',
    inputs: [{ name: 'protocolFeeRecipient', type: 'address', indexed: false, internalType: 'address' }],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'ProtocolShareBpsUpdated',
    inputs: [{ name: 'protocolShareBps', type: 'uint16', indexed: false, internalType: 'uint16' }],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'ProtocolShareOfSenderFeePctUpdated',
    inputs: [{ name: 'protocolShareOfSenderFeePct', type: 'uint8', indexed: false, internalType: 'uint8' }],
    anonymous: false,
  },
  {
    type: 'error',
    name: 'InvalidProtocolFeeRecipient',
    inputs: [{ name: 'protocolFeeRecipient', type: 'address', internalType: 'address' }],
  },
  {
    type: 'error',
    name: 'InvalidProtocolShareBps',
    inputs: [{ name: 'protocolShareBps', type: 'uint16', internalType: 'uint16' }],
  },
  {
    type: 'error',
    name: 'InvalidProtocolShareOfSenderFeePct',
    inputs: [{ name: 'protocolShareOfSenderFeePct', type: 'uint8', internalType: 'uint8' }],
  },
  { type: 'error', name: 'OwnableInvalidOwner', inputs: [{ name: 'owner', type: 'address', internalType: 'address' }] },
  {
    type: 'error',
    name: 'OwnableUnauthorizedAccount',
    inputs: [{ name: 'account', type: 'address', internalType: 'address' }],
  },
];
